-- =============================================================
-- PaskinoMercato H2 in-memory schema
-- =============================================================

CREATE SCHEMA IF NOT EXISTS mercato;

-- ---------------------------------------------------------------
-- CATEGORIES
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mercato.categoria (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codice          VARCHAR(50)  NOT NULL UNIQUE,
    nome_it         VARCHAR(100) NOT NULL,
    nome_en         VARCHAR(100) NOT NULL,
    descrizione_it  VARCHAR(2000),
    descrizione_en  VARCHAR(2000),
    immagine        VARCHAR(255)
);

-- ---------------------------------------------------------------
-- PRODUCTS
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mercato.prodotto (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codice          VARCHAR(50)     NOT NULL UNIQUE,
    nome_it         VARCHAR(200)    NOT NULL,
    nome_en         VARCHAR(200)    NOT NULL,
    descrizione_it  VARCHAR(2000),
    descrizione_en  VARCHAR(2000),
    prezzo          NUMERIC(10,2)   NOT NULL CHECK (prezzo >= 0),
    unita_misura    VARCHAR(20)     NOT NULL DEFAULT 'pz',
    quantita_stock  INTEGER         NOT NULL DEFAULT 0,
    categoria_id    INTEGER         NOT NULL REFERENCES mercato.categoria(id),
    immagine        VARCHAR(255),
    attivo          BOOLEAN         NOT NULL DEFAULT TRUE,
    peso_kg         NUMERIC(6,3),
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------
-- CUSTOMERS
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mercato.cliente (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(200)    NOT NULL UNIQUE,
    password_hash   VARCHAR(255)    NOT NULL,
    nome            VARCHAR(100)    NOT NULL,
    cognome         VARCHAR(100)    NOT NULL,
    telefono        VARCHAR(20),
    lingua          CHAR(2)         NOT NULL DEFAULT 'it' CHECK (lingua IN ('it','en')),
    attivo          BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------
-- ADDRESSES  (Italian only - validated at application level)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mercato.indirizzo (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id      INTEGER         NOT NULL REFERENCES mercato.cliente(id),
    via             VARCHAR(255)    NOT NULL,
    civico          VARCHAR(20)     NOT NULL,
    citta           VARCHAR(100)    NOT NULL,
    cap             CHAR(5)         NOT NULL,
    provincia       CHAR(2)         NOT NULL,
    paese           CHAR(2)         NOT NULL DEFAULT 'IT' CHECK (paese = 'IT'),
    predefinito     BOOLEAN         NOT NULL DEFAULT FALSE
);

-- ---------------------------------------------------------------
-- ORDERS
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mercato.ordine (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_ordine   VARCHAR(30)     NOT NULL UNIQUE,
    cliente_id      INTEGER         NOT NULL REFERENCES mercato.cliente(id),
    indirizzo_id    INTEGER         NOT NULL REFERENCES mercato.indirizzo(id),
    stato           VARCHAR(30)     NOT NULL DEFAULT 'IN_ATTESA'
                        CHECK (stato IN ('IN_ATTESA','CONFERMATO','IN_PREPARAZIONE',
                                         'SPEDITO','CONSEGNATO','ANNULLATO')),
    totale          NUMERIC(10,2)   NOT NULL CHECK (totale >= 0),
    note            VARCHAR(4000),
    email_inviata   BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------
-- ORDER LINES
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mercato.riga_ordine (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordine_id       INTEGER         NOT NULL REFERENCES mercato.ordine(id),
    prodotto_id     INTEGER         NOT NULL REFERENCES mercato.prodotto(id),
    quantita        INTEGER         NOT NULL CHECK (quantita > 0),
    prezzo_unitario NUMERIC(10,2)   NOT NULL CHECK (prezzo_unitario >= 0),
    subtotale       NUMERIC(10,2)   GENERATED ALWAYS AS (quantita * prezzo_unitario)
);

-- ---------------------------------------------------------------
-- SHOPPING CART (persisted, linked to customer)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mercato.carrello (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id      INTEGER         NOT NULL REFERENCES mercato.cliente(id),
    prodotto_id     INTEGER         NOT NULL REFERENCES mercato.prodotto(id),
    quantita        INTEGER         NOT NULL CHECK (quantita > 0),
    aggiunto_il     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (cliente_id, prodotto_id)
);

-- ---------------------------------------------------------------
-- INDEXES
-- ---------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_prodotto_categoria ON mercato.prodotto(categoria_id);
CREATE INDEX IF NOT EXISTS idx_prodotto_attivo ON mercato.prodotto(attivo);
CREATE INDEX IF NOT EXISTS idx_prodotto_nome_it ON mercato.prodotto(nome_it);
CREATE INDEX IF NOT EXISTS idx_ordine_cliente ON mercato.ordine(cliente_id);
CREATE INDEX IF NOT EXISTS idx_ordine_stato ON mercato.ordine(stato);
CREATE INDEX IF NOT EXISTS idx_carrello_cliente ON mercato.carrello(cliente_id);
